### ISSUE TITLE
error in vs code 1.17.2

### ISSUE THREAD

**Issue by antipro** [JohnstonCode/svn-scm#11]
nothing show on source control after change files

**Comment by JohnstonCode** [comment]
Hi @antipro 

Sorry to hear you are having issues. Has this only recently stopped working?

Are you getting the diffs in the gutter?

**Comment by magic-k** [comment]
I also see nothing in the source control view in 1.17.2. It just states that there is no active scm provider. svn-scm ist installed and active.

**Comment by JohnstonCode** [comment]
Is svn set in your PATH?

**Comment by magic-k** [comment]
Yes

**Comment by JohnstonCode** [comment]
Not sure what could be causing that. Working for me at the moment on two separate projects.

If you toggle the developer console are there any errors.?

**Comment by magic-k** [comment]
console.ts:123 [Extension Host] detect tortoiseSVNProcExePath
console.ts:123 [Extension Host] Error: Command failed: reg query HKEY_LOCAL_MACHINE\SOFTWARE\TortoiseSVN /v ProcPath | find /i "ProcPath"
/bin/sh: 1: reg: not found
find: "/i": Datei oder Verzeichnis nicht gefunden
find: "ProcPath": Datei oder Verzeichnis nicht gefunden

	at checkExecSyncError (child_process.js:493:13)
	at Object.execSync (child_process.js:533:13)
	at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:684:22)
	at TortoiseCommand._getTortoiseSVNProcExePath (/home/omp/.vscode/extensions/fantasytyx.tortoise-svn-0.1.1/out/src/extension.js:173:44)
	at new TortoiseCommand (/home/omp/.vscode/extensions/fantasytyx.tortoise-svn-0.1.1/out/src/extension.js:157:44)
	at activate (/home/omp/.vscode/extensions/fantasytyx.tortoise-svn-0.1.1/out/src/extension.js:21:27)
	at Function.e._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:443835)
	at Function.e._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:443580)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:442933
	at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:28:44279)
console.ts:123 [Extension Host] svn-scm is now active!

**Comment by JohnstonCode** [comment]
Can you disable tortoise-svn and dumping the console again, please.

**Comment by magic-k** [comment]
Oh, didn't see that this came from tortoise-svn. I disabled the extension, only output in debugging is 
" [Extension Host] svn-scm is now active!"
But still nothing in Source control view.

**Comment by JohnstonCode** [comment]
Thank you. I will look into this right now.

**Comment by magic-k** [comment]
Got after a while the following:
console.ts:123 [Extension Host] (node:1700) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by JohnstonCode** [comment]
Can you make sure your on version 0.8.3

Just remembered I broke 0.8.2.

**Comment by magic-k** [comment]
I'm on 0.8.3.

**Comment by JohnstonCode** [comment]
I can think what would be causing the source control not to load. 

Could be a number of things now the root is being worked out.

I have just released 0.8.4 to fix another bug with source control view not working properly. 

Give that a try.

**Comment by magic-k** [comment]
0.8.4 doesn't fix it

**Comment by JohnstonCode** [comment]
I think i know what it might be.

If you do "svn info" in the same folder as you are opening in vs code does your output look like this?

Path: .
Working Copy Root Path: /var/www/html/project
URL: svn+ssh://svn.cjohnston.net/home/shared/svn/system/branches/chris
Relative URL: ^/branches/chris
Repository Root: svn+ssh://svn.cjohnston.net/home/shared/svn/system
Repository UUID: d454355f43-fdee-0310-ad73-fdff7ff6ff6sf
Revision: 1234
Node Kind: directory
Schedule: normal
Last Changed Author: cjohnston
Last Changed Rev: 1233
Last Changed Date: 2017-11-03 10:37:20 +0100

**Comment by magic-k** [comment]
Thats my output, only difference i see is that i use http (had to replace stuff with xxx, it's a company project).

svn info
Path: .
Working Copy Root Path: G:\projects\xxx\xxx
URL: http://svn.xx.xxx.de/svn/xxx/xxx/branches/xxx/xxxApp/xxx
Relative URL: ^/xxx/branches/xxx/xxxAp/xxx
Repository Root: http://svn.xx.xxx.de/svn/xxx
Repository UUID: 1dc51510-c564-46d4-b9f3-86f09753e860
Revision: 7576
Node Kind: directory
Schedule: normal
Last Changed Author: xxxxx
Last Changed Rev: 7576
Last Changed Date: 2017-10-16 15:21:34 +0200 (Mo, 16 Okt 2017)

**Comment by JohnstonCode** [comment]
Think this will be an issue on windows the "\" I'm sure will be doing weird things.

Don't have a windows machine at work so will test when I'm at home.

Let me know if you still have the issue on Linux with the latest version.

If you do please do svn info again and only show me the "Working Copy Root Path:" line please.

**Comment by magic-k** [comment]
My Linux VM is in german:
Wurzelpfad der Arbeitskopie: /mnt/devel/xxx/project/xxxApp/xxx

**Comment by JohnstonCode** [comment]
That will be why then.

Sorry for breaking things for you!

Leave this with me ill think of something. Should have it fixed by Monday.

**Comment by magic-k** [comment]
Switched to english
Working Copy Root Path: /mnt/devel/xxx/project/xxxApp/xxx

Still not working
No problem, I'm happy there's someone working on SVN at all. I'm going home now anyway.

**Comment by JohnstonCode** [comment]
Just released 0.8.5 see if that fixes your issue.

**Comment by magic-k** [comment]
SCM viewis working again. Thanks.

**Comment by JohnstonCode** [comment]
Thanks for letting me know!

@antipro re-open this issue or create a new one if you are still having issues.
