### ISSUE TITLE
Add setting to not ignore files hidden with files.exlude

### ISSUE THREAD

**Issue by azixMcAze** [JohnstonCode/svn-scm#659]
**Is your feature request related to a problem? Please describe.**
I am using VSCode as a code editor for [Unity](https://unity.com/) and my projects are  versionned with SVN.

By default, Unity adds a `files.exclude` settings that hides a few project files extensions (scenes, models, assets, prefabs, build settings, etc.) in VSCode because they cannot be easily edited in VSCode and should instead be edited in Unity. It also removes clutter in the explorer view of VSCode, showing only code files.

However these files should be commited when they are changed. 

**Describe the solution you'd like**
I whould like a setting in the SVN extension to allow files hidden in VSCode with the `files.exclude` setting to still be visible in the SVN change list window.
The files that should be hidden from the change list window can still be configured with the `svn:ignore` property.

**Describe alternatives you've considered**
I either remove most files patterns from `files.exclude` or I use a `svn` in command line to check and commit changes

**Comment by davidcm** [comment]
Maybe this issue was overlooked, but I still find this an annoyance that could be easily solved with what azixMcAze described.

**Comment by azixMcAze** [comment]
I'd like to add that the built-in git extension does not ignore files excluded in VSCode, they can be added to git like the other files

**Comment by zhangxiaojun92163** [comment]
This problem still persists and it has become quite inconvenient. I kindly request the author to consider looking into this issue. Thank you for your time and effort.

**Comment by aianlinb** [comment]
This problem still bothers me.
Is there any suggestion for solution?
